# SPDX-FileCopyrightText: 2020 Lukas Schrangl <lukas.schrangl@tuwien.ac.at>
#
# SPDX-License-Identifier: BSD-3-Clause

package:
    name: sdt-python
    version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}{{ '.post' + environ.get('GIT_DESCRIBE_NUMBER', "0") if environ.get('GIT_DESCRIBE_NUMBER', "0") != "0" else ''}}

source:
    git_url: ../

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    noarch: python

requirements:
    host:
        - python
        - pip

    run:
        - python >=3.9
        - numpy >=1.10
        - pandas
        - pytables
        - opencv
        - pyyaml
        - numba
        - pyqt
        - matplotlib-base
        - scipy >0.18
        - tifffile >=0.14.0
        - imageio >=2.29
        - lazy_loader

test:
    requires:
        - pytest
        - trackpy
        - lmfit
        - scikit-learn
        - pims
        - pywavelets >=0.3.0
    commands:
        - pytest -v tests
    source_files:
        - tests
    imports:
        - sdt
        - sdt.brightness
        - sdt.changepoint
        - sdt.flatfield
        - sdt.fret
        - sdt.helper
        - sdt.image
        - sdt.io
        - sdt.loc
        - sdt.motion
        - sdt.multicolor
        - sdt.optimize
        - sdt.roi
        - sdt.sim
        - sdt.spatial

about:
    home: https://github.com/schuetzgroup/sdt-python
    license: BSD-3-Clause
    license_file:
        - LICENSES/BSD-3-Clause.txt
        - LICENSES/CC-BY-4.0.txt
        - LICENSES/CC0-1.0.txt
        - LICENSES/LGPL-3.0-or-later.txt
        - LICENSES/LicenseRef-Matplotlib-1.3.txt
        - LICENSES/MIT.txt
        - sdt/gui/breeze-icons/COPYING-ICONS
    summary: "Tools for fluorescence microscopy data analysis"
    dev_url: https://github.com/schuetzgroup/sdt-python
    doc_url: https://schuetzgroup.github.io/sdt-python

