"""Create files for sdt.loc.daostorm_3d.fit multiple iteration tests"""
import os

import numpy as np

from sa_library import multi_fit_c
from sa_library.multi_fit_c import multi


find_path = os.path.join("tests", "daostorm_3d", "data_find")
fit_path = os.path.join("tests", "daostorm_3d", "data_fit")
imgfile = os.path.join(find_path, "bead_img.npz")
finderfile = os.path.join(find_path, "bead_finder.npz")

frame = np.load(imgfile)["img"].astype(np.float)
peaks = np.load(finderfile)["peaks"]  # generated by `find.py`

model = "3D"
tol = 1e-6
scmos_cal = False
max_iters = 10

fitfunc = getattr(multi, "iterate"+model)

result, residual, num_iter = multi_fit_c._doFit_(
    fitfunc, frame, scmos_cal, peaks, tol, max_iters, False, 0)

outfile = os.path.join(fit_path, "beads_fit_"+model.lower()+".npz")
np.savez_compressed(outfile, peaks=result, residual=residual)
