"""Create files for sdt.loc.daostorm_3d.fit single iteration tests"""
import os

import numpy as np

from sa_library import multi_fit_c
from sa_library.multi_fit_c import multi


find_path = os.path.join("tests", "daostorm_3d", "data_find")
fit_path = os.path.join("tests", "daostorm_3d", "data_fit")
imgfile = os.path.join(find_path, "bead_img.npz")
finderfile = os.path.join(find_path, "bead_finder.npz")

frame = np.load(imgfile)["img"].astype(np.float)
peaks = np.load(finderfile)["peaks"]  # generated by `find.py`

model = "3D"
tol = 1e-6

fitfunc = getattr(multi, "iterate"+model)

multi.initialize(frame, np.zeros(frame.shape), peaks, tol,
                 frame.shape[1], frame.shape[0], len(peaks), 0)
fitfunc()
result = multi_fit_c.getResults(len(peaks))
residual = multi_fit_c.getResidual(frame.shape[0], frame.shape[1])

outfile = os.path.join(fit_path, "beads_iter_"+model.lower()+".npz")
np.savez_compressed(outfile, peaks=result, residual=residual)
